const Strings = {
  Login: 'Log in',
  EnterBarcodeCode: 'Enter Barcode code',
  EnterBarcodeCodeHere: 'Enter Barcode code Here...',
  Submit: 'Submit',
  SubmitCode: 'Submit Code',
  Or: 'Or',
  ScanBarCode: 'Scan Barcode',
  Username: 'Username',
  Email: 'Email',
  Enteryourusername: 'Enter your username',
  Enteryouremail: 'Enter your email',
  Password: 'Password',
  EnteryourPassword: 'Enter your Password',
  BarcodeID: 'Barcode ID',
  UploadPhoto: 'Upload Photo',
  Upload: 'Upload',
  PhotoSuccessfullyUploaded: 'Photo Successfully Uploaded',
  BackToHome: 'Back To Home',
  NoCameraPermission: 'Please give camera permission to use device camera.',
  RequestPermission: 'Request Permission',
  Google: 'Google',
  Facebook: 'Facebook',
  BarcodeScanner: 'Barcode Scanner',
  PreviewUploadImages: 'Preview Upload Images',
};

export default Strings;
